$(function(){
    $("open-btn").on('click',function(){
        $('#popup-box').addClass('.show');
    });
    $(function(){
        $("close-btn").on('click',function(){
            $('#popup-box').removeClass('.show');
        });
    });
});